# Generated by Django 4.1.3 on 2023-07-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytuto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='meta_description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='meta_tags',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
