# Generated by Django 4.1.3 on 2023-10-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytuto', '0002_tutorial_meta_description_tutorial_meta_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tutorial',
            new_name='pytuto',
        ),
    ]
