# Generated by Django 4.1.3 on 2023-07-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactModel',
        ),
    ]
